version: '2'
services:
    jenkins:
        build: ./jenkins
        container_name: jenkins
        privileged: true
        restart: always
        ports:
            - "80:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home/
            - /var/run/docker.sock:/var/run/docker.sock

    nodejs:
        build: ./nodejs
        container_name: nodejs
        privileged: true
        restart: always
        ports:
            - 22
        volumes_from:
            - jenkins
volumes:
    jenkins-data:
        driver: local
