version: '2'
services:
    jenkins:
        build:
            context: .
        container_name: jenkins
        privileged: true
        restart: always
        ports:
            - "80:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home/
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    jenkins-data:
        driver: local
